Feature/order
wecode-bootcamp-korea/13-monawe-backend pull request #3
Opened 2020-10-21 05:03 UTC by mgm-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 / 찜목록 / 리뷰를 관리하는 앱 order 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- models.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- order 앱의 models.py가 user 앱과 prodcut 앱을 참조합니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-21 13:33 UTC, soheon-lee commented on order/models.py
> +        return self.name
`self.name`이 없는데 지정하신건가요?

2020-10-21 13:33 UTC, soheon-lee commented on order/models.py
> +    tracking_number = models.CharField(max_length=45)
`=`을 기준으로 정렬해주세요

2020-10-21 13:33 UTC, soheon-lee commented on order/models.py
> +class OrderStatus(models.Model):
Order테이블과 Status 테이블의 중간테이블인가요? 이렇게 지정해주신 이유가 따로 있나요? 하나의 주문이 여러 Status를 동시에 갖는 다는 의미인가요? 댓글로 달아주세요~ :-)

2020-10-21 13:33 UTC, soheon-lee commented on order/models.py
> +        return self.name
코드 전반에 걸쳐 이 구문이 많은데 모두 이렇게 지정하신건가요?

2020-10-22 02:10 UTC, mgm-dev commented on order/models.py
> +    tracking_number = models.CharField(max_length=45)
간격 수정했습니다 :)

2020-10-22 02:37 UTC, mgm-dev commented on order/models.py
> +class OrderStatus(models.Model):
다 대 다로 설정하면 관리가 편할 것이라고 생각했었습니다. 다시 생각해보니 order : status는 다 대 일로 하는 것이 맞는 것 같아요. 해당 부분 수정했습니다 :)

2020-10-22 02:40 UTC, mgm-dev commented on order/models.py
> +        return self.name
해당 부분은 제가 실수 한 것 같습니다 :(
불필요한 구문들 삭제했습니다!

2020-10-22 09:54 UTC, lordmyshepherd requested changes

2020-10-22 09:54 UTC, lordmyshepherd commented on product/models.py
> +class ProductTag(models.Model):  # middle table
product와 tag에 many to many field를 선언해주세요!

2020-10-22 12:21 UTC, mgm-dev commented on product/models.py
> +class ProductTag(models.Model):  # middle table
tag 테이블에 many to many field 선언했습니다 :)

2020-10-22 12:55 UTC, soheon-lee commented on product/views.py
> +        return JsonResponse(data, safe=False)
views 는 현재 review 대상이 아닙니당 :) 백업해두시고 코드 잠깐 지워주세요~ 리뷰할 것들이 많아서 models와는 별개로 진행하겠습니다 ~

2020-10-22 13:27 UTC, mgm-dev commented on product/views.py
> +        return JsonResponse(data, safe=False)
넵 삭제했습니다!

2020-10-23 02:19 UTC, soheon-lee commented
LGTM

2020-10-23 02:19 UTC, merged