[13기 monawe] 회원정보 관련 뷰 작성
wecode-bootcamp-korea/13-monawe-backend pull request #4
Opened 2020-10-23 02:15 UTC by mgm-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원 정보 관련 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 뷰 : 이메일 형식 검사, 비밀번호 길이 검사, 이메일 중복, 아이디 중복 검사
- 로그인 뷰 : 토큰 발행
- 이메일 / 아이디 중복 검사 뷰 : 프론트의 요청으로 개별 뷰 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- django 뷰를 짜는 컨벤션이 궁금합니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-26 07:38 UTC, lordmyshepherd requested changes

2020-10-26 07:38 UTC, lordmyshepherd commented on product/urls.py
> +# from product.views import All, Category, Subcategory
주석은 지워주세요~

2020-10-26 07:38 UTC, lordmyshepherd commented on product/urls.py
> +    # path('all', All.as_view()),
마찬가지 입니다~

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +        except KeyError:
위 코드에서 KeyError가 날 수 있는 부분은 어디인가요??

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +        data  = json.loads(request.body)
만약에 json data가 잘 못 들어오는 경우 에러가 발생할 수 있을까요?

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +            dateString = data.get('dateOfBirth')
```suggestion
            date_string = data.get('dateOfBirth')
```

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +        except IntegrityError:
어떤 경우에 IntegrityError가 발생하나요?

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER_ID"}, status=401)
resource가 duplicate되는 경우 409 error를 return 해주는 것 이 정확합니다.~

2020-10-26 07:38 UTC, lordmyshepherd commented on user/views.py
> +                user = User.objects.get(account=data.get('account'))
위에서 filter().exist() 할 때, db hit를 하번 하고 get()을 실행할 때, 또 한번 db를 hit 합니다. 
추가로 get()의 경우 data를 찾지 못 할 경우 DoseNotExist Error를 raise합니다. 하지만 아래에서 error를 잡아주지 않고 있는 것 처럼 보이네요. 두 가지를 고려해서 코드를 수정해주세요~
혹시 제가 잘 못 이해하고 있는 부분이 있으면 말씀해주세요~~

2020-10-26 08:31 UTC, lordmyshepherd requested changes

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +        except KeyError:
마찬가지 입니다. key error가 어떤 경우에 발생하나요??

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +            if duplicate:
한줄로 수정해주세요~
```suggestion
            if User.objects.filter(email=data.get('email')).exists():
```

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +        except ValidationError:
validation Error는 어떤 경우에 발생하나요?

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +class CheckEmail(View):
email의 존재 여부를 확인해주는 엔드포인트 인가요??

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +            if duplicate:
```suggestion
            if User.objects.filter(account=data.get('account')).exists():
```

2020-10-26 08:31 UTC, lordmyshepherd commented on user/views.py
> +        user_info = User.objects.get(id=user_id)
get()으로 데이터를 조회할 경우, DoseNotExist Error가 발생할 수 있습니다.
예외처리 해주세요~~

2020-10-26 09:32 UTC, mgm-dev commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER_ID"}, status=401)
409로 수정했습니다 :)

2020-10-26 09:35 UTC, mgm-dev commented on product/urls.py
> +# from product.views import All, Category, Subcategory
삭제 하겠습니다!

2020-10-26 09:35 UTC, mgm-dev commented on product/urls.py
> +    # path('all', All.as_view()),
넵 이것도 삭제하겠습니다

2020-10-26 09:37 UTC, mgm-dev commented on user/views.py
> +            dateString = data.get('dateOfBirth')
스네이크체로 수정했습니다 :)

2020-10-26 09:40 UTC, mgm-dev commented on user/views.py
> +            if duplicate:
불필요한 변수 삭제 했습니다 :)

2020-10-26 09:42 UTC, mgm-dev commented on user/views.py
> +            if duplicate:
이부분도 수정했습니다 :)

2020-10-26 10:42 UTC, mgm-dev commented on user/views.py
> +        except IntegrityError:
프론트에서 보낸 JSON의 문제로 인해(ex: 키 누락), user 테이블의 스키마에 맞지 않는 로우를 생성하려고 할때 일어날 수 있다고 생각했습니다.

2020-10-26 10:43 UTC, mgm-dev commented on user/views.py
> +class CheckEmail(View):
네, 이메일 중복 검사를 위한 엔드포인트 입니다

2020-10-26 10:50 UTC, mgm-dev commented on user/views.py
> +        user_info = User.objects.get(id=user_id)
User.DoesNotExist 예외 처리 추가했습니다 :)

2020-10-26 11:05 UTC, mgm-dev commented on user/views.py
> +                user = User.objects.get(account=data.get('account'))
filter를 사용할 때 결과를 변수에 저장해서, db에 퀴리를 두번 날리지 않게 바꿔보았습니다 :)

2020-10-26 11:20 UTC, mgm-dev commented on user/views.py
> +        data  = json.loads(request.body)
JSONDecodeError가 발생할 수 있습니다. 해당 부분 및 json.loads() 하는 코드를 try 문 안으로 이동시켰습니다 :)

2020-10-26 11:21 UTC, mgm-dev commented on user/views.py
> +        except ValidationError:
이 부분의 경우 제 실수 였습니다. ValueError로 수정했습니다!

2020-10-26 11:49 UTC, mgm-dev commented on user/views.py
> +        except KeyError:
.get() 메서드를 사용해서 불필요 합니다! 해당 예외처리 삭제했습니다 :)

2020-10-26 11:49 UTC, mgm-dev commented on user/views.py
> +        except KeyError:
해당 예외처리 삭제했습니다 :)

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +            password_crypt = password_crypt.decode('utf-8')
```suggestion
            password_crypt = bcrypt.hashpw(password, bcrypt.gensalt()).decode('utf-8')
```
굳이 두 번에 분리하시지 않고 한 번에 처리하셔도 좋습니다

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +        except IntegrityError:
키가 누락 되었을 경우에는 KeyError가 만들어져야 합니다 :-) 그래야 프론트엔드에서 누락된 키 값을 알 수 있기 때문입니다.

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +            user = User.objects.filter(account=data.get('account'))
email을 이용해 접근할 user가 오직 단 한명 뿐이기 때문에 `filter()` 메소드가 아닌 `get`을 바로 사용하셔도 됩니다.

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +            if bcrypt.checkpw(data.get('password').encode('UTF-8'), user[0].password.encode('UTF-8')):
57번 줄에서 `get`을 사용하신다면 여기서`[0]`으로 첫번째 데이터에 접근하지 않으셔도 됩니다.

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +                token     = jwt.encode({'user' : user[0].id},key, algorithm = algorithm).decode('UTF-8')
여기도 마찬가지입니다. 유저 한 명에 접근 하기 위해 숫자 0을 반복해서 사용하고 있습니다. 이와 같은 하드 코딩을 줄이시는 것이 좋습니다 :)

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
else가 없어도 바로 위의 if문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 else를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. 지워주셔도 됩니다 :)

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message" : "USER_EMAIL_OK"}, status=200)
else가 없어도 바로 위의 if문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 else를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. 지워주셔도 됩니다 :)

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message" : "USER_ID_OK"}, status=200)
else가 없어도 바로 위의 if문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 else를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. 지워주셔도 됩니다 :)

2020-10-27 05:55 UTC, soheon-lee commented on user/views.py
> +                "date_of_birth" : user_info.date_of_birth
코드 간격 정렬해주세요

2020-10-27 06:29 UTC, mgm-dev commented on user/views.py
> +            password_crypt = password_crypt.decode('utf-8')
싱글라인으로 수정했습니다 :)

2020-10-27 06:41 UTC, mgm-dev commented on user/views.py
> +            user = User.objects.filter(account=data.get('account'))
get 메서드로 수정했습니다!

2020-10-27 06:42 UTC, mgm-dev commented on user/views.py
> +            if bcrypt.checkpw(data.get('password').encode('UTF-8'), user[0].password.encode('UTF-8')):
넵 해당 부분도 수정했습니다 :)

2020-10-27 06:43 UTC, mgm-dev commented on user/views.py
> +                token     = jwt.encode({'user' : user[0].id},key, algorithm = algorithm).decode('UTF-8')
수정했습니다!

2020-10-27 06:44 UTC, mgm-dev commented on user/views.py
> +                return JsonResponse({"message" : "USER_EMAIL_OK"}, status=200)
불필요한 else 문 삭제했습니다 :)

2020-10-27 06:45 UTC, mgm-dev commented on user/views.py
> +                "date_of_birth" : user_info.date_of_birth
수직 정렬했습니다 :)

2020-10-27 06:47 UTC, mgm-dev commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
넵 삭제하겠습니다!

2020-10-27 06:47 UTC, mgm-dev commented on user/views.py
> +                return JsonResponse({"message" : "USER_ID_OK"}, status=200)
불필요한 else 문 삭제했습니다 :)

2020-10-27 06:56 UTC, mgm-dev commented on user/views.py
> +        except IntegrityError:
프론트에서 알아보기 쉽게 에러 메시지를 수정했습니다!

2020-10-28 06:26 UTC, lordmyshepherd requested changes

2020-10-28 06:26 UTC, lordmyshepherd commented on user/views.py
> +class CheckEmail(View):
그냥 두셔도 괜찮을 것 같습니다~

2020-10-28 06:26 UTC, lordmyshepherd commented on user/views.py
> +        except IntegrityError:
IntegrityError는 경민님께서 말씀하신대로, schema에 value를 insert할 때 발생하는 에러입니다.
key 값이 누락된 경우 data.get('')으로 key값에 접근하게되면, 에러를 raise하는게 아니라 None을 반환합니다.

그렇기 때문에 Null값을 schema에 insert할 때, IntegrityError가 발생하는 것이죠.
이 경우에는 data['key']로 접근하고, KeyError를 잡아주고, IntegrityError는 피하는게 좋습니다.
application 실행 단에서 에러를 잡아주는게 좋습니다~

2020-10-28 06:26 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({"data" : data}, status=400)
```suggestion
            return JsonResponse({"data" : data}, status=200)
```

2020-10-28 06:26 UTC, lordmyshepherd commented on user/views.py
> +            ).save()
get_or_create() method를 사용해보시면 좋을 것 같습니다~

2020-10-28 06:26 UTC, lordmyshepherd commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=409)
`User.objects.get()`으로 데이터를 조회할 경우, 객체를 찾지 못하면, UserDoseNotExist Error를 raise합니다!
그렇기 때문에 
if not user: 
    return JsonResponse... 부분은 사용되지 않습니다.

<2가지 방법>
1. filter().eixsts()로 존재여부 확인 --> User.DoesNotExist 사용 X
2. get() --> User.DoesNotExist 사용 O

2020-10-28 09:46 UTC, mgm-dev commented on user/views.py
> +        except IntegrityError:
KeyError raise 하게 수정했습니다!

2020-10-28 09:47 UTC, mgm-dev commented on user/views.py
> +            return JsonResponse({"data" : data}, status=400)
typo 수정했습니다 :)

2020-10-28 09:51 UTC, mgm-dev commented on user/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=409)
불필요한 if 절 삭제 했습니다!

2020-10-29 10:54 UTC, lordmyshepherd approved these changes

2020-10-29 10:54 UTC, lordmyshepherd commented
LGTM 👍

2020-10-29 11:04 UTC, merged