[13기 monawe] 상품 정보 관련 뷰 작성
wecode-bootcamp-korea/13-monawe-backend pull request #5
Opened 2020-10-23 05:37 UTC by mgm-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 정보 관련 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- All : 전체 상품 목록 리턴하는 뷰 
- Category & Subcategory : 카테고리/서브카테고리로 상품 목록 필터링 후 목록 리턴하는 뷰
- Detail : 상품 상세 정보를 리턴하는 뷰

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- django 뷰를 작성하는 컨벤션이 궁금합니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-26 08:38 UTC, lordmyshepherd requested changes

2020-10-26 08:38 UTC, lordmyshepherd commented on product/models.py
> +        return data
get_info method는 여러 군대에서 호출해서 사용되나요?

2020-10-26 08:40 UTC, lordmyshepherd commented
뷰 작성이 맞나요??

2020-10-26 11:51 UTC, mgm-dev commented on product/models.py
> +        return data
네. 추후 찜목록, 주문 목록 등에서 사용 될 수 있다고 생각했습니다.

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +
offset, limit, item_per_page 변수화 정말 잘하셨습니다 :) 
현재 서브카테고리 id와 카테고리 id 가 들어오느냐 마느냐에 따라 코드가 분기되고 있는데, 사실 조건만 다를 뿐, 다른 코드는 같은 상태입니다. 따라서 여러 옵셔널한 (있을 수도 있고 없을 수도 있는) 컨디션만 달리 하고 elif, else 사이에 중복된 코드는 제거하실 수 있을 것 같습니다.

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +
리스트 컴프리헨션을 활용해보세요 :) 일반 for loop보다 2배 가량 속도가 빠릅니다.

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +
Search 뷰도 결국 Product 데이터에 접근하는 엔드포인트입니다. 따라서 RESTful API 관점에서 ProductList뷰와 같은 엔드포인트라고 할 수 있습니다. 두 클래스의 get 함수를 합쳐보세요 :)

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +class Review(View):
CRUD가 모두 있네요 !! 굳!

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +            for product_option in ProductOption.objects.filter(product=product):
82번째 줄에서 product 객체를 선택하셨기 때문에 연결된 옵션을 가져올 때 ProductOption클래스에 새로 접근하시기 보다 역참조로 연결되어있는 속성에서 가져오도록 해보세요 :)

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +                option['price'] = product.price + product_option.plus_price
```suggestion
                body         = {
                    'name' : product_option.body_color.name
                    ....
                }
                
```
과 같이 선언하시면 불필요한 빈 딕셔너리를 선언하지 않아도 되고, 그 이름을 계속 쓰지 않아도 되어서 편리합니다 :)

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +
여기 전부 list comprehension 내부로 넣어서 선언해보세요 :)

2020-10-27 06:08 UTC, soheon-lee commented on product/views.py
> +            }
모든 클래스에 독립적으로 접근하면, 매번 `SELECT * from ` 쿼리가 날아가게 됩니다 :) 이미 product 객체가 선언되었으므로 연결된 속성이라는 공통점을 이용해 접근해보세요

2020-10-27 07:14 UTC, mgm-dev commented on product/views.py
> +
성능이 그렇게 차이 나는 것 처음 알았습니다! 앞으로 리스트 컴프리헨션 적극 사용하겠습니당 :)

2020-10-27 07:23 UTC, mgm-dev commented on product/views.py
> +
ProductList 뷰에서 search 쿼리 스트링을 체크하는 방식으로 수정했습니다 :)

2020-10-27 07:26 UTC, mgm-dev commented on product/views.py
> +class Review(View):
감사합니다 :+1:

2020-10-27 07:33 UTC, mgm-dev commented on product/views.py
> +                option['price'] = product.price + product_option.plus_price
수정했습니다. 훨씬 깔끔해진 것 같아요 :)

2020-10-27 08:11 UTC, mgm-dev commented on product/views.py
> +            for product_option in ProductOption.objects.filter(product=product):
_set 방식으로 접근하게 변경했습니다 :)

2020-10-27 08:30 UTC, mgm-dev commented on product/views.py
> +            }
역참조 후, 쿼리 셋을 변수에 저장 하는 방식으로 불필요한 중복 쿼리를 줄여봤습니다 :)

2020-10-27 08:41 UTC, mgm-dev commented on product/views.py
> +
배열 별로 리스트 컴프리헨션 적용 해봤습니다!

2020-10-27 09:55 UTC, mgm-dev commented on product/views.py
> +
필터링 조건을 딕셔너리로 저장하고, if else 문에서 해당 딕셔너리를 수정 하는 방식으로 변경해봤습니다 :)

2020-10-28 07:09 UTC, lordmyshepherd requested changes

2020-10-28 07:09 UTC, lordmyshepherd commented on product/views.py
> +            ]
아래 loggin을 settings.py에 추가해서 퀴리 수를 측정해보시면 좋을 것 같습니다~
```
LOGGING = {
    'disable_existing_loggers': False,
    'version': 1,
    'formatters': {
         'verbose': {
            'format': '{asctime} {levelname} {message}',
            'style': '{'
        },
    },
    'handlers': {
        'console': {
            'class'     : 'logging.StreamHandler',
            'formatter' : 'verbose',
            'level'     : 'DEBUG',
        },
        'file': {
            'level'     : 'DEBUG',
            'class'     : 'logging.FileHandler',
            'formatter' : 'verbose',
            'filename'  : 'debug.log',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers' : ['console','file'],
            'level'    : 'DEBUG',
            'propagate': False,
        },
    },
}
```

2020-10-28 07:09 UTC, lordmyshepherd commented on product/views.py
> +            product_tag_list    = product.producttag_set.all()
prefetch_related()를 사용해보시면 좋을 것 같습니다~
작성하신 코드와 prefetch_related()를 사용했을 때, 차이를 확인해보시면 좋을 것 같습니다~

2020-10-28 08:49 UTC, mgm-dev commented on product/views.py
> +            ]
settings.py에 추가 하겠습니다 :)

2020-10-28 10:50 UTC, mgm-dev commented on product/views.py
> +            product_tag_list    = product.producttag_set.all()
prefetch_related()를 추가했습니다. 쿼리 수가 1/3로 줄었습니다!

2020-10-28 13:11 UTC, soheon-lee commented
LGTM

2020-10-28 13:11 UTC, merged